version: "3.2"

networks:
  kadmos-net:

services:

  kadmos-data-a:
    image: postgres
    container_name: 'kadmos-data-a'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kadmos
      - POSTGRES_PASSWORD=Pass2020!
      - POSTGRES_DB=kadmos_a
    networks:
      - kadmos-net

  kadmos-data-b:
    image: postgres
    container_name: 'kadmos-data-b'
    command: -p 5433
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=kadmos
      - POSTGRES_PASSWORD=Pass2020!
      - POSTGRES_DB=kadmos_b
    networks:
      - kadmos-net

  saving-service-a:
    image: savings
    container_name: 'saving-service-a'
    environment:
      - SPRING_PROFILES_ACTIVE=demoa
    expose:
      - 9001
    ports:
      - 9001:8081
    networks:
      - kadmos-net

  saving-service-b:
    image: savings
    container_name: 'saving-service-b'
    environment:
      - SPRING_PROFILES_ACTIVE=demob
    expose:
      - 9002
    ports:
      - 9002:8082
    networks:
      - kadmos-net

  gateway:
    image: api-gateway
    container_name: 'gateway'
    ports:
      - 8080:8080
    networks:
      - kadmos-net
