version: "3.2"

networks:
  kadmos-net:

services:
  kadmos-data-a:
    image: postgres
    container_name: 'kadmos-data-a'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kadmos
      - POSTGRES_PASSWORD=Pass2020!
      - POSTGRES_DB=kadmos_a
    networks:
      - kadmos-net

  kadmos-data-b:
    image: postgres
    container_name: 'kadmos-data-b'
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=kadmos
      - POSTGRES_PASSWORD=Pass2020!
      - POSTGRES_DB=kadmos_b
    networks:
      - kadmos-net

  saving-service-a:
    image: savings-a
    container_name: 'saving-service-a'
    ports:
      - 9001:8081
    networks:
      - kadmos-net

  saving-service-b:
    image: savings-a
    container_name: 'saving-service-a'
    ports:
      - 9001:8082
    networks:
      - kadmos-net

  gateway:
    image: api-gateway
    container_name: 'gateway'
    ports:
      - 8080:8080
    networks:
      - kadmos-net
