version: "3.2"

networks:
  kadmos-net:

services:
  kadmos-data:
    image: postgres
    container_name: 'kadmos-data'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kadmos
      - POSTGRES_PASSWORD=Pass2020!
      - POSTGRES_DB=kadmos
    networks:
      - kadmos-net

  saving-service-a:
    image: savings-a
    container_name: 'saving-service-a'
    ports:
      - 8081:8081
    networks:
      - kadmos-net

  gateway:
    image: api-gateway
    container_name: 'gateway'
    ports:
      - 8080:8080
    networks:
      - kadmos-net
